### ISSUE TITLE
Cert files not work

### ISSUE THREAD

**Issue by hakaiderii** [xoseperez/the-things-stack-docker#3]
hi Xoseperez,

1. I try to add these lines below to docker-compose.yml

  ```
      secrets:
        - ca.pem
        - cert.pem
        - key.pem
  # If using custom certificates:
  secrets:
    ca.pem:
       file: ./ca.pem
    cert.pem:
      file: ./cert.pem
    key.pem:
      file: ./key.pem
```

2. I create SSL Cert follow this guideline https://www.thethingsindustries.com/docs/the-things-stack/host/docker/certificates/#using-custom-certificates

3. i try to import ca.pem to Microsoft Management Console under certificate folder or try to import certificate in Browers but it still now recoginize by browser. Could you please help me with this issue ?
![image](https://github.com/xoseperez/the-things-stack-docker/assets/38075885/47d82b28-6d70-4d9a-9b07-6385aff23994)
![image](https://github.com/xoseperez/the-things-stack-docker/assets/38075885/3a26e579-c84e-4943-9d97-453756dfe55f)
